falter-common: pick the ip-tiny variant
Recent fixes to APK dependency logic in snapshot and 25.12 result in
virtual packages like `ip` now being forbidden in EXTRA_DEPENDS.

    ERROR: unable to select packages:
      ip-tiny-6.18.0-r1:
        breaks: falter-common-5[ip>=0]
        satisfies: world[ip]
                   wireguard-tools-1.0.20250521-r1[ip]

So let's be specific about ip-tiny, it's the right thing to do anyway.

Signed-off-by: Packet Please <pktpls@systemli.org>
(cherry picked from commit 84b3dfdb20f2738de0c88d81c276571e43ce8d94)