treewide: add mandatory version constraints for EXTRA_DEPENDS
See https://github.com/openwrt/openwrt/pull/20819

Due to our heavy use of EXTRA_DEPENDS, we got the following error
for each of our many dependencies:

    Makefile:69: *** "Extra dependencies must have version constraints. falter-berlin-autoupdate-keys seems to be unversioned.".  Stop.
    make[2]: Leaving directory '/home/user/w/ff/falter-packages/packages/falter-berlin-autoupdate'
    time: package/feeds/falter/falter-berlin-autoupdate/compile#0.07#0.03#0.09
        ERROR: package/feeds/falter/falter-berlin-autoupdate failed to build.

When using only regular DEPENDS, all kmods are built for each occurence
of a kmod dependency. It seems to be a bug in the SDK, though I haven't
had time to investigate it properly. Since this results in a 500%+
increase in build times, we continue to use EXTRA_DEPENDS for now.

Signed-off-by: Packet Please <pktpls@systemli.org>
(cherry picked from commit 816cf4575e542eca2e3ac453bc350077aaac292e)