luci-mod-falter: Fix "Undefined reference to net.iwdata"
(cherry picked from commit 7508005bd0518bc0601a026264cefc00d4f13f03)
(cherry picked from commit 2e8d3c8e8bd40904c00fdc0e6fbf6b74c1832796)